// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import BuildingController from "./building_controller";
application.register("building", BuildingController);

import SelectController from "./select_controller";
application.register("select", SelectController);

import RadioController from "./radio_controller";
application.register("radio", RadioController);
